/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "rtl/uart_rx.v:1" *)
module uart_rx(clk, rst_n, rx, data_out, valid);
  (* src = "rtl/uart_rx.v:23" *)
  wire [12:0] _000_;
  (* src = "rtl/uart_rx.v:23" *)
  wire [3:0] _001_;
  (* src = "rtl/uart_rx.v:23" *)
  wire [7:0] _002_;
  (* src = "rtl/uart_rx.v:23" *)
  wire [7:0] _003_;
  (* src = "rtl/uart_rx.v:23" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  (* src = "rtl/uart_rx.v:12" *)
  reg [12:0] baud_cnt;
  (* src = "rtl/uart_rx.v:13" *)
  reg [3:0] bit_cnt;
  (* src = "rtl/uart_rx.v:2" *)
  input clk;
  (* src = "rtl/uart_rx.v:5" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  (* src = "rtl/uart_rx.v:3" *)
  input rst_n;
  (* src = "rtl/uart_rx.v:4" *)
  input rx;
  (* src = "rtl/uart_rx.v:14" *)
  reg [7:0] shift_reg;
  (* onehot = 32'd1 *)
  reg [3:0] state;
  (* src = "rtl/uart_rx.v:6" *)
  output valid;
  reg valid;
  assign _159_ = baud_cnt[1] & baud_cnt[0];
  assign _160_ = baud_cnt[3] | ~(baud_cnt[2]);
  assign _161_ = _159_ & ~(_160_);
  assign _162_ = baud_cnt[5] | ~(baud_cnt[4]);
  assign _163_ = baud_cnt[7] | ~(baud_cnt[6]);
  assign _164_ = _163_ | _162_;
  assign _165_ = _161_ & ~(_164_);
  assign _166_ = baud_cnt[9] | baud_cnt[8];
  assign _167_ = baud_cnt[11] | ~(baud_cnt[10]);
  assign _168_ = _167_ | _166_;
  assign _169_ = baud_cnt[12] & ~(_168_);
  assign _170_ = ~(_169_ & _165_);
  assign _004_ = state[3] & ~(_170_);
  assign _171_ = rx & state[0];
  assign _005_ = _171_ | _004_;
  assign _172_ = ~state[1];
  assign _173_ = ~(_170_ & state[3]);
  assign _174_ = ~(bit_cnt[1] & bit_cnt[0]);
  assign _175_ = bit_cnt[3] | ~(bit_cnt[2]);
  assign _176_ = ~(_175_ | _174_);
  assign _177_ = _170_ | ~(_176_);
  assign _008_ = ~((_177_ | _172_) & _173_);
  assign _178_ = ~state[2];
  assign _009_ = ~state[0];
  assign _010_ = baud_cnt[2] | ~(baud_cnt[3]);
  assign _011_ = _159_ & ~(_010_);
  assign _012_ = baud_cnt[4] | ~(baud_cnt[5]);
  assign _013_ = baud_cnt[7] | baud_cnt[6];
  assign _014_ = _013_ | _012_;
  assign _015_ = _011_ & ~(_014_);
  assign _016_ = baud_cnt[8] | ~(baud_cnt[9]);
  assign _017_ = baud_cnt[10] | ~(baud_cnt[11]);
  assign _018_ = _017_ | _016_;
  assign _019_ = _018_ | baud_cnt[12];
  assign _020_ = _015_ & ~(_019_);
  assign _007_ = ~((_020_ | _178_) & (rx | _009_));
  assign _021_ = ~((_020_ & state[2]) | (_170_ & state[1]));
  assign _022_ = _176_ | _170_;
  assign _006_ = ~((_022_ | _172_) & _021_);
  assign _023_ = state[1] | state[3];
  assign _024_ = _023_ | state[2];
  assign _025_ = _009_ & ~(_024_);
  assign _026_ = _170_ & ~(baud_cnt[0]);
  assign _027_ = ~(_020_ | baud_cnt[0]);
  assign _028_ = ~((_027_ & state[2]) | (_026_ & _023_));
  assign _029_ = ~(rx & baud_cnt[0]);
  assign _030_ = ~((_029_ | _009_) & _028_);
  assign _000_[0] = _025_ ? baud_cnt[0] : _030_;
  assign _031_ = ~(baud_cnt[1] ^ baud_cnt[0]);
  assign _032_ = _170_ & ~(_031_);
  assign _033_ = ~(_031_ | _020_);
  assign _034_ = ~((_033_ & state[2]) | (_032_ & _023_));
  assign _035_ = ~(rx & baud_cnt[1]);
  assign _036_ = ~((_035_ | _009_) & _034_);
  assign _000_[1] = _025_ ? baud_cnt[1] : _036_;
  assign _037_ = ~(baud_cnt[1] & baud_cnt[0]);
  assign _038_ = _037_ ^ baud_cnt[2];
  assign _039_ = _170_ & ~(_038_);
  assign _040_ = ~(_038_ | _020_);
  assign _041_ = ~((_040_ & state[2]) | (_039_ & _023_));
  assign _042_ = ~(rx & baud_cnt[2]);
  assign _043_ = ~((_042_ | _009_) & _041_);
  assign _000_[2] = _025_ ? baud_cnt[2] : _043_;
  assign _044_ = ~(_159_ & baud_cnt[2]);
  assign _045_ = _044_ ^ baud_cnt[3];
  assign _046_ = _170_ & ~(_045_);
  assign _047_ = ~(_045_ | _020_);
  assign _048_ = ~((_047_ & state[2]) | (_046_ & _023_));
  assign _049_ = ~(rx & baud_cnt[3]);
  assign _050_ = ~((_049_ | _009_) & _048_);
  assign _000_[3] = _025_ ? baud_cnt[3] : _050_;
  assign _051_ = ~(baud_cnt[3] & baud_cnt[2]);
  assign _052_ = _051_ | _037_;
  assign _053_ = _052_ ^ baud_cnt[4];
  assign _054_ = _170_ & ~(_053_);
  assign _055_ = ~(_053_ | _020_);
  assign _056_ = ~((_055_ & state[2]) | (_054_ & _023_));
  assign _057_ = ~(rx & baud_cnt[4]);
  assign _058_ = ~((_057_ | _009_) & _056_);
  assign _000_[4] = _025_ ? baud_cnt[4] : _058_;
  assign _059_ = _159_ & ~(_051_);
  assign _060_ = ~(_059_ & baud_cnt[4]);
  assign _061_ = _060_ ^ baud_cnt[5];
  assign _062_ = _170_ & ~(_061_);
  assign _063_ = ~(_061_ | _020_);
  assign _064_ = ~((_063_ & state[2]) | (_062_ & _023_));
  assign _065_ = ~(rx & baud_cnt[5]);
  assign _066_ = ~((_065_ | _009_) & _064_);
  assign _000_[5] = _025_ ? baud_cnt[5] : _066_;
  assign _067_ = ~(baud_cnt[5] & baud_cnt[4]);
  assign _068_ = _067_ | _052_;
  assign _069_ = _068_ ^ baud_cnt[6];
  assign _070_ = _170_ & ~(_069_);
  assign _071_ = ~(_069_ | _020_);
  assign _072_ = ~((_071_ & state[2]) | (_070_ & _023_));
  assign _073_ = ~(rx & baud_cnt[6]);
  assign _074_ = ~((_073_ | _009_) & _072_);
  assign _000_[6] = _025_ ? baud_cnt[6] : _074_;
  assign _075_ = _068_ | ~(baud_cnt[6]);
  assign _076_ = _075_ ^ baud_cnt[7];
  assign _077_ = _170_ & ~(_076_);
  assign _078_ = ~_020_;
  assign _079_ = _078_ & ~(_076_);
  assign _080_ = ~((_079_ & state[2]) | (_077_ & _023_));
  assign _081_ = ~(rx & baud_cnt[7]);
  assign _082_ = ~((_081_ | _009_) & _080_);
  assign _000_[7] = _025_ ? baud_cnt[7] : _082_;
  assign _083_ = ~(baud_cnt[7] & baud_cnt[6]);
  assign _084_ = _083_ | _067_;
  assign _085_ = _059_ & ~(_084_);
  assign _086_ = ~(_085_ ^ baud_cnt[8]);
  assign _087_ = _170_ & ~(_086_);
  assign _088_ = ~(_086_ | _020_);
  assign _089_ = ~((_088_ & state[2]) | (_087_ & _023_));
  assign _090_ = ~(rx & baud_cnt[8]);
  assign _091_ = ~((_090_ | _009_) & _089_);
  assign _000_[8] = _025_ ? baud_cnt[8] : _091_;
  assign _092_ = ~(_085_ & baud_cnt[8]);
  assign _093_ = _092_ ^ baud_cnt[9];
  assign _094_ = _170_ & ~(_093_);
  assign _095_ = _078_ & ~(_093_);
  assign _096_ = ~((_095_ & state[2]) | (_094_ & _023_));
  assign _097_ = ~(rx & baud_cnt[9]);
  assign _098_ = ~((_097_ | _009_) & _096_);
  assign _000_[9] = _025_ ? baud_cnt[9] : _098_;
  assign _099_ = ~(baud_cnt[9] & baud_cnt[8]);
  assign _100_ = _099_ | ~(_085_);
  assign _101_ = _100_ ^ baud_cnt[10];
  assign _102_ = _170_ & ~(_101_);
  assign _103_ = _078_ & ~(_101_);
  assign _104_ = ~((_103_ & state[2]) | (_102_ & _023_));
  assign _105_ = ~(rx & baud_cnt[10]);
  assign _106_ = ~((_105_ | _009_) & _104_);
  assign _000_[10] = _025_ ? baud_cnt[10] : _106_;
  assign _107_ = _100_ | ~(baud_cnt[10]);
  assign _108_ = _107_ ^ baud_cnt[11];
  assign _109_ = _170_ & ~(_108_);
  assign _110_ = _078_ & ~(_108_);
  assign _111_ = ~((_110_ & state[2]) | (_109_ & _023_));
  assign _112_ = ~(rx & baud_cnt[11]);
  assign _113_ = ~((_112_ | _009_) & _111_);
  assign _000_[11] = _025_ ? baud_cnt[11] : _113_;
  assign _114_ = ~(baud_cnt[11] & baud_cnt[10]);
  assign _115_ = _114_ | _099_;
  assign _116_ = _115_ | ~(_085_);
  assign _117_ = _116_ ^ baud_cnt[12];
  assign _118_ = _170_ & ~(_117_);
  assign _119_ = _078_ & ~(_117_);
  assign _120_ = ~((_119_ & state[2]) | (_118_ & _023_));
  assign _121_ = ~(rx & baud_cnt[12]);
  assign _122_ = ~((_121_ | _009_) & _120_);
  assign _000_[12] = _025_ ? baud_cnt[12] : _122_;
  assign _123_ = _170_ ? data_out[0] : shift_reg[0];
  assign _002_[0] = state[3] ? _123_ : data_out[0];
  assign _124_ = _170_ ? data_out[1] : shift_reg[1];
  assign _002_[1] = state[3] ? _124_ : data_out[1];
  assign _125_ = _170_ ? data_out[2] : shift_reg[2];
  assign _002_[2] = state[3] ? _125_ : data_out[2];
  assign _126_ = _170_ ? data_out[3] : shift_reg[3];
  assign _002_[3] = state[3] ? _126_ : data_out[3];
  assign _127_ = _170_ ? data_out[4] : shift_reg[4];
  assign _002_[4] = state[3] ? _127_ : data_out[4];
  assign _128_ = _170_ ? data_out[5] : shift_reg[5];
  assign _002_[5] = state[3] ? _128_ : data_out[5];
  assign _129_ = _170_ ? data_out[6] : shift_reg[6];
  assign _002_[6] = state[3] ? _129_ : data_out[6];
  assign _130_ = _170_ ? data_out[7] : shift_reg[7];
  assign _002_[7] = state[3] ? _130_ : data_out[7];
  assign _131_ = _170_ ? shift_reg[0] : shift_reg[1];
  assign _003_[0] = state[1] ? _131_ : shift_reg[0];
  assign _132_ = _170_ ? shift_reg[1] : shift_reg[2];
  assign _003_[1] = state[1] ? _132_ : shift_reg[1];
  assign _133_ = _170_ ? shift_reg[2] : shift_reg[3];
  assign _003_[2] = state[1] ? _133_ : shift_reg[2];
  assign _134_ = _170_ ? shift_reg[3] : shift_reg[4];
  assign _003_[3] = state[1] ? _134_ : shift_reg[3];
  assign _135_ = _170_ ? shift_reg[4] : shift_reg[5];
  assign _003_[4] = state[1] ? _135_ : shift_reg[4];
  assign _136_ = _170_ ? shift_reg[5] : shift_reg[6];
  assign _003_[5] = state[1] ? _136_ : shift_reg[5];
  assign _137_ = _170_ ? shift_reg[6] : shift_reg[7];
  assign _003_[6] = state[1] ? _137_ : shift_reg[6];
  assign _138_ = _170_ ? shift_reg[7] : rx;
  assign _003_[7] = state[1] ? _138_ : shift_reg[7];
  assign _139_ = ~(state[1] | state[2]);
  assign _140_ = _170_ ^ bit_cnt[0];
  assign _141_ = _020_ | ~(bit_cnt[0]);
  assign _142_ = ~((_141_ | _178_) & (_140_ | _172_));
  assign _001_[0] = _139_ ? bit_cnt[0] : _142_;
  assign _143_ = ~bit_cnt[1];
  assign _144_ = ~(bit_cnt[1] ^ bit_cnt[0]);
  assign _145_ = _170_ ? _143_ : _144_;
  assign _146_ = _020_ | _143_;
  assign _147_ = ~((_146_ | _178_) & (_145_ | _172_));
  assign _001_[1] = _139_ ? bit_cnt[1] : _147_;
  assign _148_ = ~bit_cnt[2];
  assign _149_ = _174_ ^ bit_cnt[2];
  assign _150_ = _170_ ? _148_ : _149_;
  assign _151_ = _020_ | _148_;
  assign _152_ = ~((_151_ | _178_) & (_150_ | _172_));
  assign _001_[2] = _139_ ? bit_cnt[2] : _152_;
  assign _153_ = ~bit_cnt[3];
  assign _154_ = bit_cnt[2] & ~(_174_);
  assign _155_ = _154_ ^ _153_;
  assign _156_ = _170_ ? _153_ : _155_;
  assign _157_ = _020_ | _153_;
  assign _158_ = ~((_157_ | _178_) & (_156_ | _172_));
  assign _001_[3] = _139_ ? bit_cnt[3] : _158_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      state[0] <= 1;
    else
      state[0] <= _005_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      state[1] <= 0;
    else
      state[1] <= _006_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      state[2] <= 0;
    else
      state[2] <= _007_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      state[3] <= 0;
    else
      state[3] <= _008_;
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[0] <= 0;
    else
      baud_cnt[0] <= _000_[0];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[1] <= 0;
    else
      baud_cnt[1] <= _000_[1];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[2] <= 0;
    else
      baud_cnt[2] <= _000_[2];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[3] <= 0;
    else
      baud_cnt[3] <= _000_[3];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[4] <= 0;
    else
      baud_cnt[4] <= _000_[4];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[5] <= 0;
    else
      baud_cnt[5] <= _000_[5];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[6] <= 0;
    else
      baud_cnt[6] <= _000_[6];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[7] <= 0;
    else
      baud_cnt[7] <= _000_[7];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[8] <= 0;
    else
      baud_cnt[8] <= _000_[8];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[9] <= 0;
    else
      baud_cnt[9] <= _000_[9];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[10] <= 0;
    else
      baud_cnt[10] <= _000_[10];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[11] <= 0;
    else
      baud_cnt[11] <= _000_[11];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[12] <= 0;
    else
      baud_cnt[12] <= _000_[12];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      bit_cnt[0] <= 0;
    else
      bit_cnt[0] <= _001_[0];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      bit_cnt[1] <= 0;
    else
      bit_cnt[1] <= _001_[1];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      bit_cnt[2] <= 0;
    else
      bit_cnt[2] <= _001_[2];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      bit_cnt[3] <= 0;
    else
      bit_cnt[3] <= _001_[3];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      shift_reg[0] <= 0;
    else
      shift_reg[0] <= _003_[0];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      shift_reg[1] <= 0;
    else
      shift_reg[1] <= _003_[1];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      shift_reg[2] <= 0;
    else
      shift_reg[2] <= _003_[2];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      shift_reg[3] <= 0;
    else
      shift_reg[3] <= _003_[3];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      shift_reg[4] <= 0;
    else
      shift_reg[4] <= _003_[4];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      shift_reg[5] <= 0;
    else
      shift_reg[5] <= _003_[5];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      shift_reg[6] <= 0;
    else
      shift_reg[6] <= _003_[6];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      shift_reg[7] <= 0;
    else
      shift_reg[7] <= _003_[7];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      data_out[0] <= 0;
    else
      data_out[0] <= _002_[0];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      data_out[1] <= 0;
    else
      data_out[1] <= _002_[1];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      data_out[2] <= 0;
    else
      data_out[2] <= _002_[2];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      data_out[3] <= 0;
    else
      data_out[3] <= _002_[3];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      data_out[4] <= 0;
    else
      data_out[4] <= _002_[4];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      data_out[5] <= 0;
    else
      data_out[5] <= _002_[5];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      data_out[6] <= 0;
    else
      data_out[6] <= _002_[6];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      data_out[7] <= 0;
    else
      data_out[7] <= _002_[7];
  (* src = "rtl/uart_rx.v:23" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      valid <= 0;
    else
      valid <= _004_;
endmodule

(* top =  1  *)
(* src = "rtl/uart_top.v:1" *)
module uart_top(clk, rst_n, start, tx_data, rx, tx, rx_data, rx_valid, busy);
  (* src = "rtl/uart_top.v:10" *)
  output busy;
  (* src = "rtl/uart_top.v:2" *)
  input clk;
  (* src = "rtl/uart_top.v:3" *)
  input rst_n;
  (* src = "rtl/uart_top.v:6" *)
  input rx;
  (* src = "rtl/uart_top.v:8" *)
  output [7:0] rx_data;
  (* src = "rtl/uart_top.v:9" *)
  output rx_valid;
  (* src = "rtl/uart_top.v:4" *)
  input start;
  (* src = "rtl/uart_top.v:7" *)
  output tx;
  (* src = "rtl/uart_top.v:5" *)
  input [7:0] tx_data;
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/uart_top.v:22" *)
  uart_rx rx_inst (
    .clk(clk),
    .data_out(rx_data),
    .rst_n(rst_n),
    .rx(rx),
    .valid(rx_valid)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/uart_top.v:13" *)
  uart_tx tx_inst (
    .busy(busy),
    .clk(clk),
    .data_in(tx_data),
    .rst_n(rst_n),
    .start(start),
    .tx(tx)
  );
endmodule

(* src = "rtl/uart_tx.v:1" *)
module uart_tx(clk, rst_n, start, data_in, tx, busy);
  (* src = "rtl/uart_tx.v:17" *)
  wire [12:0] _000_;
  (* src = "rtl/uart_tx.v:17" *)
  wire [3:0] _001_;
  (* src = "rtl/uart_tx.v:17" *)
  wire _002_;
  (* src = "rtl/uart_tx.v:17" *)
  wire [9:0] _003_;
  (* src = "rtl/uart_tx.v:17" *)
  wire _004_;
  (* src = "rtl/uart_tx.v:17" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  (* src = "rtl/uart_tx.v:12" *)
  reg [12:0] baud_cnt;
  (* src = "rtl/uart_tx.v:13" *)
  reg [3:0] bit_cnt;
  (* src = "rtl/uart_tx.v:7" *)
  output busy;
  reg busy;
  (* src = "rtl/uart_tx.v:2" *)
  input clk;
  (* src = "rtl/uart_tx.v:5" *)
  input [7:0] data_in;
  (* src = "rtl/uart_tx.v:3" *)
  input rst_n;
  (* src = "rtl/uart_tx.v:14" *)
  reg [9:0] shift_reg;
  (* src = "rtl/uart_tx.v:4" *)
  input start;
  (* src = "rtl/uart_tx.v:15" *)
  reg transmitting;
  (* src = "rtl/uart_tx.v:6" *)
  output tx;
  reg tx;
  assign _104_ = ~(baud_cnt[1] & baud_cnt[0]);
  assign _105_ = baud_cnt[3] | ~(baud_cnt[2]);
  assign _106_ = _105_ | _104_;
  assign _107_ = baud_cnt[5] | ~(baud_cnt[4]);
  assign _108_ = baud_cnt[7] | ~(baud_cnt[6]);
  assign _109_ = _108_ | _107_;
  assign _110_ = _109_ | _106_;
  assign _111_ = ~baud_cnt[12];
  assign _112_ = baud_cnt[9] | baud_cnt[8];
  assign _113_ = baud_cnt[11] | ~(baud_cnt[10]);
  assign _114_ = _113_ | _112_;
  assign _115_ = _114_ | _111_;
  assign _116_ = ~(_115_ | _110_);
  assign _117_ = _116_ ? shift_reg[0] : tx;
  assign _118_ = transmitting ? _117_ : tx;
  assign _119_ = start & ~(transmitting);
  assign _120_ = ~_119_;
  assign _005_ = _119_ ? tx : _118_;
  assign _121_ = _116_ ? shift_reg[1] : shift_reg[0];
  assign _122_ = transmitting ? _121_ : shift_reg[0];
  assign _003_[0] = _122_ & ~(_119_);
  assign _123_ = _116_ ? shift_reg[2] : shift_reg[1];
  assign _124_ = transmitting ? _123_ : shift_reg[1];
  assign _003_[1] = _119_ ? data_in[0] : _124_;
  assign _125_ = _116_ ? shift_reg[3] : shift_reg[2];
  assign _126_ = transmitting ? _125_ : shift_reg[2];
  assign _003_[2] = _119_ ? data_in[1] : _126_;
  assign _127_ = _116_ ? shift_reg[4] : shift_reg[3];
  assign _128_ = transmitting ? _127_ : shift_reg[3];
  assign _003_[3] = _119_ ? data_in[2] : _128_;
  assign _006_ = _116_ ? shift_reg[5] : shift_reg[4];
  assign _007_ = transmitting ? _006_ : shift_reg[4];
  assign _003_[4] = _119_ ? data_in[3] : _007_;
  assign _008_ = _116_ ? shift_reg[6] : shift_reg[5];
  assign _009_ = transmitting ? _008_ : shift_reg[5];
  assign _003_[5] = _119_ ? data_in[4] : _009_;
  assign _010_ = _116_ ? shift_reg[7] : shift_reg[6];
  assign _011_ = transmitting ? _010_ : shift_reg[6];
  assign _003_[6] = _119_ ? data_in[5] : _011_;
  assign _012_ = _116_ ? shift_reg[8] : shift_reg[7];
  assign _013_ = transmitting ? _012_ : shift_reg[7];
  assign _003_[7] = _119_ ? data_in[6] : _013_;
  assign _014_ = _116_ ? shift_reg[9] : shift_reg[8];
  assign _015_ = transmitting ? _014_ : shift_reg[8];
  assign _003_[8] = _119_ ? data_in[7] : _015_;
  assign _016_ = ~((_116_ & transmitting) | shift_reg[9]);
  assign _003_[9] = ~(_016_ & _120_);
  assign _017_ = ~bit_cnt[0];
  assign _018_ = _116_ ^ _017_;
  assign _019_ = transmitting ? _018_ : _017_;
  assign _001_[0] = _120_ & ~(_019_);
  assign _020_ = ~bit_cnt[1];
  assign _021_ = ~(bit_cnt[0] ^ bit_cnt[1]);
  assign _022_ = _116_ ? _021_ : _020_;
  assign _023_ = transmitting ? _022_ : _020_;
  assign _001_[1] = _120_ & ~(_023_);
  assign _024_ = ~bit_cnt[2];
  assign _025_ = ~(bit_cnt[0] & bit_cnt[1]);
  assign _026_ = _025_ ^ bit_cnt[2];
  assign _027_ = _116_ ? _026_ : _024_;
  assign _028_ = transmitting ? _027_ : _024_;
  assign _001_[2] = _120_ & ~(_028_);
  assign _029_ = ~bit_cnt[3];
  assign _030_ = bit_cnt[2] & ~(_025_);
  assign _031_ = _030_ ^ _029_;
  assign _032_ = _116_ ? _031_ : _029_;
  assign _033_ = transmitting ? _032_ : _029_;
  assign _001_[3] = _120_ & ~(_033_);
  assign _034_ = ~(_116_ | baud_cnt[0]);
  assign _035_ = transmitting ? _034_ : baud_cnt[0];
  assign _000_[0] = _035_ & ~(_119_);
  assign _036_ = baud_cnt[1] ^ baud_cnt[0];
  assign _037_ = _036_ & ~(_116_);
  assign _038_ = transmitting ? _037_ : baud_cnt[1];
  assign _000_[1] = _038_ & ~(_119_);
  assign _039_ = baud_cnt[1] & baud_cnt[0];
  assign _040_ = _039_ ^ baud_cnt[2];
  assign _041_ = _040_ & ~(_116_);
  assign _042_ = transmitting ? _041_ : baud_cnt[2];
  assign _000_[2] = _042_ & ~(_119_);
  assign _043_ = baud_cnt[2] & ~(_104_);
  assign _044_ = _043_ ^ baud_cnt[3];
  assign _045_ = _044_ & ~(_116_);
  assign _046_ = transmitting ? _045_ : baud_cnt[3];
  assign _000_[3] = _046_ & ~(_119_);
  assign _047_ = ~(baud_cnt[2] & baud_cnt[3]);
  assign _048_ = _039_ & ~(_047_);
  assign _049_ = _048_ ^ baud_cnt[4];
  assign _050_ = _049_ & ~(_116_);
  assign _051_ = transmitting ? _050_ : baud_cnt[4];
  assign _000_[4] = _051_ & ~(_119_);
  assign _052_ = ~baud_cnt[5];
  assign _053_ = _047_ | _104_;
  assign _054_ = baud_cnt[4] & ~(_053_);
  assign _055_ = _054_ ^ _052_;
  assign _056_ = _055_ | _116_;
  assign _057_ = transmitting ? _056_ : _052_;
  assign _000_[5] = _120_ & ~(_057_);
  assign _058_ = ~(baud_cnt[4] & baud_cnt[5]);
  assign _059_ = _058_ | _053_;
  assign _060_ = ~(_059_ ^ baud_cnt[6]);
  assign _061_ = _060_ & ~(_116_);
  assign _062_ = transmitting ? _061_ : baud_cnt[6];
  assign _000_[6] = _062_ & ~(_119_);
  assign _063_ = ~baud_cnt[7];
  assign _064_ = ~_116_;
  assign _065_ = baud_cnt[6] & ~(_059_);
  assign _066_ = _065_ ^ _063_;
  assign _067_ = _066_ | ~(_064_);
  assign _068_ = transmitting ? _067_ : _063_;
  assign _000_[7] = _120_ & ~(_068_);
  assign _069_ = ~baud_cnt[8];
  assign _070_ = ~(baud_cnt[6] & baud_cnt[7]);
  assign _071_ = _070_ | _058_;
  assign _072_ = _048_ & ~(_071_);
  assign _073_ = _072_ ^ _069_;
  assign _074_ = _073_ | _116_;
  assign _075_ = transmitting ? _074_ : _069_;
  assign _000_[8] = _120_ & ~(_075_);
  assign _076_ = ~baud_cnt[9];
  assign _077_ = _072_ & ~(_069_);
  assign _078_ = _077_ ^ _076_;
  assign _079_ = _078_ | ~(_064_);
  assign _080_ = transmitting ? _079_ : _076_;
  assign _000_[9] = _120_ & ~(_080_);
  assign _081_ = ~(baud_cnt[9] & baud_cnt[8]);
  assign _082_ = _081_ | ~(_072_);
  assign _083_ = _082_ ^ baud_cnt[10];
  assign _084_ = _064_ & ~(_083_);
  assign _085_ = transmitting ? _084_ : baud_cnt[10];
  assign _000_[10] = _085_ & ~(_119_);
  assign _086_ = ~baud_cnt[11];
  assign _087_ = baud_cnt[10] & ~(_082_);
  assign _088_ = _087_ ^ _086_;
  assign _089_ = _088_ | ~(_064_);
  assign _090_ = transmitting ? _089_ : _086_;
  assign _000_[11] = _120_ & ~(_090_);
  assign _091_ = ~(baud_cnt[10] & baud_cnt[11]);
  assign _092_ = _091_ | _081_;
  assign _093_ = _072_ & ~(_092_);
  assign _094_ = _093_ ^ _111_;
  assign _095_ = _094_ | ~(_064_);
  assign _096_ = transmitting ? _095_ : _111_;
  assign _000_[12] = _120_ & ~(_096_);
  assign _097_ = bit_cnt[0] & ~(bit_cnt[1]);
  assign _098_ = bit_cnt[2] | ~(bit_cnt[3]);
  assign _099_ = _097_ & ~(_098_);
  assign _100_ = ~(_099_ & _116_);
  assign _004_ = transmitting ? _100_ : start;
  assign _101_ = ~busy;
  assign _102_ = ~((_099_ & _116_) | _101_);
  assign _103_ = transmitting ? _102_ : busy;
  assign _002_ = _103_ | _119_;
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk)
      shift_reg[0] <= _003_[0];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk)
      shift_reg[1] <= _003_[1];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk)
      shift_reg[2] <= _003_[2];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk)
      shift_reg[3] <= _003_[3];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk)
      shift_reg[4] <= _003_[4];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk)
      shift_reg[5] <= _003_[5];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk)
      shift_reg[6] <= _003_[6];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk)
      shift_reg[7] <= _003_[7];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk)
      shift_reg[8] <= _003_[8];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk)
      shift_reg[9] <= _003_[9];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[0] <= 0;
    else
      baud_cnt[0] <= _000_[0];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[1] <= 0;
    else
      baud_cnt[1] <= _000_[1];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[2] <= 0;
    else
      baud_cnt[2] <= _000_[2];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[3] <= 0;
    else
      baud_cnt[3] <= _000_[3];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[4] <= 0;
    else
      baud_cnt[4] <= _000_[4];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[5] <= 0;
    else
      baud_cnt[5] <= _000_[5];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[6] <= 0;
    else
      baud_cnt[6] <= _000_[6];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[7] <= 0;
    else
      baud_cnt[7] <= _000_[7];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[8] <= 0;
    else
      baud_cnt[8] <= _000_[8];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[9] <= 0;
    else
      baud_cnt[9] <= _000_[9];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[10] <= 0;
    else
      baud_cnt[10] <= _000_[10];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[11] <= 0;
    else
      baud_cnt[11] <= _000_[11];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      baud_cnt[12] <= 0;
    else
      baud_cnt[12] <= _000_[12];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      bit_cnt[0] <= 0;
    else
      bit_cnt[0] <= _001_[0];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      bit_cnt[1] <= 0;
    else
      bit_cnt[1] <= _001_[1];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      bit_cnt[2] <= 0;
    else
      bit_cnt[2] <= _001_[2];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      bit_cnt[3] <= 0;
    else
      bit_cnt[3] <= _001_[3];
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      tx <= 1;
    else
      tx <= _005_;
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      busy <= 0;
    else
      busy <= _002_;
  (* src = "rtl/uart_tx.v:17" *)
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      transmitting <= 0;
    else
      transmitting <= _004_;
endmodule
